# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2671a94971b2a9ee595dd258be08c27e5ec8d4a5d8920ecf9c357027dc5ebb77966a199995793c9ce120f15548c0e8bc8eac66061fbe81c9c4474820a0189aba

test:
  secret_key_base: 72b6f9e6818b13f6a7b9c352d199c91b62dcb37814d20b24208d719ea0e0493646e7847cef6d789ab11bfbfab39e82f19caaa15b876542e258d801417bcaebab

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
